# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EAPLI5sXiyx9WTI1ftyYEaLVkl2AE-qv
"""

!pip install streamlit

import streamlit as st
import pickle
import pandas as pd
import gzip # Import the gzip library

# Load model
@st.cache_resource
def load_model():
    # Use gzip.open to decompress the file before unpickling
    with gzip.open('/content/arima_model (1).pkl.gz', 'rb') as f:
        model_fit = pickle.load(f)
    return model_fit

# Load data
@st.cache_data
def load_data():
    df = pd.read_csv('aquifers_fe.csv', parse_dates=['Date'], index_col='Date')
    ts = df['Actual_Depth']  # Make sure this matches your column name
    return ts

model_fit = load_model()
ts_data = load_data()

# UI
st.title("⛲ Aquifer Depth Forecast Dashboard")
st.write("### Historical Actual Depth")
st.line_chart(ts_data)

# Sidebar
forecast_steps = st.sidebar.number_input("Forecast Days", min_value=1, max_value=50, value=10)

# Forecast
forecast = model_fit.forecast(steps=forecast_steps)
forecast_index = pd.date_range(ts_data.index[-1] + pd.Timedelta(days=1), periods=forecast_steps, freq='D')
forecast_series = pd.Series(forecast, index=forecast_index)

# Output
st.write(f"### Forecast for Next {forecast_steps} Days")
st.line_chart(forecast_series)

